only red-color host name

diff --git a/tmux-cssh b/tmux-cssh
--- a/tmux-cssh
+++ b/tmux-cssh
@@ -312,7 +312,7 @@ for host in ${HOSTS[@]}; do
 		  initTmuxCall="false"
     fi
 	else
-    tmux split-window -t "${TMUX_SESSION_NAME}" "${connectString} || { echo -e '${red_background}Error connecting to $host${end_color}'; sleep 20s; }" && \
+    tmux split-window -t "${TMUX_SESSION_NAME}" "${connectString} || { echo -e 'Error connecting to ${red_background}$host${end_color}'; sleep 20s; }" && \
     tmux select-layout -t "${TMUX_SESSION_NAME}" "${TMUX_LAYOUT}"
 	fi
 done
